# docker-compose.yml

services:
  # Baza danych PostgreSQL z rozszerzeniem pgvector dla wektorów embeddings
  db:
    image: ankane/pgvector:v0.5.1
    environment:
      POSTGRES_DB: knowledge_db      # Nazwa bazy danych
      POSTGRES_USER: user           # Użytkownik bazy danych
      POSTGRES_PASSWORD: password   # Hasło do bazy danych
    volumes:
      - pg_data:/var/lib/postgresql/data # Trwałe przechowywanie danych
    ports:
      - "5432:5432"  # Mapowanie portu PostgreSQL
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  # Cache Redis dla sesji i tymczasowych danych
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"  # Mapowanie portu Redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  # Serwis backend (FastAPI + Python)
  backend:
    build: ./backend              # Budowanie z lokalnego Dockerfile
    volumes:
      - ./backend:/app            # Montowanie kodu dla development
      - backend_uploads:/app/app/uploaded_pdfs  # Trwałe przechowywanie PDF-ów
    ports:
      - "8000:8000"              # Mapowanie portu API
    depends_on:
      db:
        condition: service_healthy    # Czeka na gotowość bazy danych
      redis:
        condition: service_healthy    # Czeka na gotowość Redis
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/knowledge_db
      REDIS_URL: redis://redis:6379
      CORS_ORIGINS: http://localhost:3000,http://127.0.0.1:3000,http://frontend:3000
    restart: unless-stopped

  # Serwis frontend (React - tryb deweloperski)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app            # Montowanie kodu dla development
      - /app/node_modules         # Oddzielny wolumen dla node_modules
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8000  # URL do backendu
    depends_on:
      - backend
    restart: unless-stopped

# Wolumeny dla trwałego przechowywania danych
volumes:
  pg_data:        # Wolumen dla danych PostgreSQL
  backend_uploads:  # Wolumen dla przesłanych plików PDF
